config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      delete 'destroy_all'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts,          only: [:show,:create, :destroy] do 
    resources :comments,         only: [:create, :destroy]
    resource :likes,                    only:[:create, :destroy]
    collection do
      get 'search'
    end
  end 
  resources :notifications,        only:[:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def terms_of_service
  end

  def privacy_policy
  end
end

app/views/static_pages/home.html.erb
<% set_meta_tags title: 'ホーム' %>
<% if logged_in? %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

<% else %>
<div class="center jumbotron">
  <h1>Insta Clone</h1>
  <h2>
  Insta clone is an app with compact sns function.
  </h2>
  <%= link_to image_tag("article_pc_GettyImages-542551148.jpg", alt: "camera picture", class: "top-image" ),
  "https://p1-16efdeae.imageflux.jp/default/image/image/1166919091302732728/article_pc_GettyImages-542551148.jpg" %>
  <p>
    <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary", id: "sign up btn" %>
  </p>
</div>

<% end %>

app/views/static_pages/privacy_policy.html.erb
<% set_meta_tags title: 'プライバシーポリシー', destroy: 'Insta Cloneのプライバシーポリシーページです。'%>

<% provide(:title, 'Privacy_policy') %>

<h1>プライバシーポリシー</h1>
<br>
<div class="privacy_policy-container">
  <p>
    高橋 寿明（以下，「当方」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
  </p><br>
  <p>
    <strong>第1条（個人情報）</strong><br>
    「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
  </p><br>
  <p>
    <strong>第2条（個人情報の収集方法）</strong><br>
    当方は，ユーザーが利用登録をする際に氏名，性別，電話番号，メールアドレスなどの個人情報をお尋ねすることがあります。
  <p><br>
  <p>
    <strong>第3条（個人情報を収集・利用する目的）</strong><br>
    当社が個人情報を収集・利用する目的は，以下のとおりです。<br>
    <ol>
      <li>当方サービスの提供・運営のため</li>
      <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
      <li>ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため</li>
      <li>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
      <li>利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</li>
      <li>ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</li>
      <li>上記の利用目的に付随する目的</li>
    </ol>
  <p>
    <strong>第4条（利用目的の変更）</strong><br>
    <ol>
      <li>当方は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。</li>
      <li>利用目的の変更を行った場合には，変更後の目的について，当方所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</li>
    </ol>
  </p><br>
  <p>
    <strong>第5条（個人情報の第三者提供）</strong><br>
    <ol>
      <li>当方は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</li><br>
      <ol>
        <li>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
        <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
        <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
        <li>予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき</li><br>
        <ol>
          <li>利用目的に第三者への提供を含むこと</li>
          <li>第三者に提供されるデータの項目</li>
          <li>第三者への提供の手段または方法</li>
          <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
          <li>本人の求めを受け付ける方法</li><br>
        </ol>
      </ol>
      <li>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。</li><br>
        <ol>
          <li>当方が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
          <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
          <li>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
        </ol>
    </ol>
  </p><br>
  <p>
    <strong>第6条（個人情報の開示）</strong><br>
    <ol>
      <li>当方は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。</li><br>
      <ol>
        <li>本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</li>
        <li>当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
        <li>その他法令に違反することとなる場合</li><br>
      </ol>
      <li>前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</li>
    </ol>
  </p><br>
  <p>
    <strong>第7条（個人情報の訂正および削除）</strong><br>
    <ol>
      <li>ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。</li>
      <li>当方は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。</li>
      <li>当方は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</li>
    </ol>
  </p><br>
  <p>
    <strong>第8条（個人情報の利用停止等）</strong><br>
    <ol>
      <li>当方は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</li>
      <li>当方は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</li>
      <li>当方は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。</li>
      <li>前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</li>
    </ol>
  </p><br>
  <p>
    <strong>第9条（プライバシーポリシーの変更）</strong><br>
    <ol>
      <li>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</li>
      <li>当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
    </ol>
  </p><br>
  <p>
    <strong>第10条（お問い合わせ窓口）</strong><br>
    本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。
    <ul>
      <li>address : ×××××××××××××××××××</li>
      <li>name : Toshiaki Takahashi</li>
      <li>email : ×××××××××××××××××××</li>
  </p><br><br>
  that's all
</div><br>

<button type="button">
  <%= link_to "Terms_of_service", terms_of_service_path, class: "btn btn-secondary" %>
</button>

<button type="button">
  <%= link_to "Signup", signup_path, class: "btn btn-secondary" %>
</button> 

app/views/static_pages/terms_of_service.html.erb
<% set_meta_tags title: 'Terms of service', destroy: 'Insta Cloneの利用規約です。'%>

<% provide(:title, 'Terms of service') %>

<h1>利用規約</h1>
<br>
<div class="terms-of-service-container">
  <p>
    この利用規約（以下，「本規約」といいます。）は，高橋 寿明（以下，「当方」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
  </p><br>
  <p>
    <strong>第1条（適用）</strong><br>
    本規約は，ユーザーと当方との間の本サービスの利用に関わる一切の関係に適用されるものとします。<br>
    当方は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。<br>
    本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。
  </p><br>
  <p>
    <strong>第2条（利用登録）</strong><br>
    本サービスにおいては，登録希望者が本規約に同意の上，当方の定める方法によって利用登録を申請し，当方がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。<br>
    当方は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。<br>
    <ul>
      <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
      <li>本規約に違反したことがある者からの申請である場合</li>
      <li>その他，当方が利用登録を相当でないと判断した場合</li>
    </ul>
  </p><br>
  <p>
    <strong>第3条（ユーザーIDおよびパスワードの管理）</strong><br>
    ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。<br>
    ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当方は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。<br>
    ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当方に故意又は重大な過失がある場合を除き，当方は一切の責任を負わないものとします。
  </p><br>
  <p>
    <strong>第4条（禁止事項）</strong><br>
    ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。<br>
    <ul>
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>当方，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
      <li>当方のサービスの運営を妨害するおそれのある行為</li>
      <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
      <li>不正アクセスをし，またはこれを試みる行為</li>
      <li>他のユーザーに成りすます行為</li>
      <li>当方のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
      <li>当方，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
    </ul><br>
    以下の表現を含み，または含むと当方が判断する内容を本サービス上に投稿し，または送信する行為<br>
    <ul>
      <li>過度に暴力的な表現</li>
      <li>露骨な性的表現</li>
      <li>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
      <li>自殺，自傷行為，薬物乱用を誘引または助長する表現</li>
      <li>その他反社会的な内容を含み他人に不快感を与える表現</li>
    </ul><br>
    以下を目的とし，または目的とすると当社が判断する行為<br>
    <ul>
      <li>営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。）</li>
      <li>性行為やわいせつな行為を目的とする行為</li>
      <li>面識のない異性との出会いや交際を目的とする行為</li>
      <li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
      <li>当社，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
      <li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
      <li>宗教活動または宗教団体への勧誘行為</li>
      <li>その他，当方が不適切と判断する行為</li>
    </ul>
  </p><br>
  <p>
    <strong>第5条（本サービスの提供の停止等）</strong><br>
    当方は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
    <ul>
      <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
      <li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
      <li>コンピュータまたは通信回線等が事故により停止した場合</li>
      <li>その他，当方が本サービスの提供が困難と判断した場合</li>
    </ul>
    当方は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。
  </p><br>
  <p>
    <strong>第6条（著作権）</strong><br>
    ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。<br>
    ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当方は，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。<br>
    前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当方または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。
  </p><br>
  <p>
    <strong>第7条（利用制限および登録抹消）</strong><br>
    当方は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。<br>
    <ul>
      <li>本規約のいずれかの条項に違反した場合</li>
      <li>登録事項に虚偽の事実があることが判明した場合</li>
      <li>当方からの連絡に対し，一定期間返答がない場合</li>
      <li>本サービスについて，最終の利用から一定期間利用がない場合</li>
      <li>その他，当方が本サービスの利用を適当でないと判断した場合</li>
    </ul>
    前項各号のいずれかに該当した場合，ユーザーは，当然に当方に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。<br>
    当方は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。
  </p><br>
  <p>
    <strong>第8条（退会）</strong><br>
    ユーザーは，当方の定める退会手続により，本サービスから退会できるものとします。
  </p><br>
  <p>
    <strong>第9条（保証の否認および免責事項）</strong><br>
    当方は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。<br>
    当方は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当方とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。<br>
    当方は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
  </p><br>
  <p>
    <strong>第10条（サービス内容の変更等）</strong><br>
    当方は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
  </p><br>
  <p>
    <strong>第11条（利用規約の変更）</strong><br>
    当方は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
  </p><br>
  <p>
    <strong>第12条（個人情報の取扱い）</strong><br>
    当方は，本サービスの利用によって取得する個人情報については，当方「
    <%= link_to "プライバシーポリシー", privacy_policy_path %>
    」に従い適切に取り扱うものとします。
  </p><br>
  <p>
    <strong>第13条（通知または連絡）</strong><br>
    ユーザーと当方との間の通知または連絡は，当方の定める方法によって行うものとします。当方は,ユーザーから,当方が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
  </p><br>
  <p>
    <strong>第14条（権利義務の譲渡の禁止）</strong><br>
    ユーザーは，当方の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
  </p><br>
  <p>
    <strong>第15条（準拠法・裁判管轄）</strong><br>
    本規約の解釈にあたっては，日本法を準拠法とします。<br>
    本サービスに関して紛争が生じた場合には，当方の所在地を管轄する裁判所を専属的合意管轄とします。<br><br>
    以上
</div><br>

<button type="button">
  <%= link_to "PrivacyPolicy", privacy_policy_path, class: "btn btn-secondary" %>
</button>

<button type="button">
  <%= link_to "SignUp", signup_path, class: "btn btn-secondary" %>
  </button> 