config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      delete 'destroy_all'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts,          only: [:show,:create, :destroy] do 
    resources :comments,         only: [:create, :destroy]
    resource :likes,                    only:[:create, :destroy]
    collection do
      get 'search'
    end
  end 
  resources :notifications,        only:[:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :micropost, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.paginate(page: params[:page])
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    Notification.destroy_all
    redirect_to notifications_path
  end
end

app/views/notifications/_circle.html.erb
<% if unchecked_notifications.any? %>
  <span class="circle">
    <i class="fa fa-circle" style="color: gold;"></i>
  </span>
<% end %>
<li>
  <%= link_to notifications_path do %>
    <i class="fa fa-bell fa-2x"></i>
  <% end %>
</li> 

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% micropost = notification.micropost %>

<div class="notification-view clearfix">
  <%= link_to user_path(visitor) do %>
    <%= gravatar_for visitor, size: 50 %>
    <strong><%= visitor.name %></strong>
  <% end %>
  <span>さん</span>
  <%= notification_form(notification) %>
  <br>
  <% if !@comment.nil? %>
    <p class="moderate-font" style="color: #C0C0C0;"><%= @comment %></p>
  <% end %>
  <span class="moderate-font">
    <%= " #{time_ago_in_words(notification.created_at)}前" %>
  </span>
  <hr>
</div>

app/views/notifications/index.html.erb
<% set_meta_tags title: '通知', description: 'Inssta Clone アカウントのいいねやコメントを受け取り通知をします。' %>
<% provide(:title, "Notifications") %>
<h1>Notification</h1>
  <%= link_to destroy_all_notifications_path(current_user), method: :delete,
              data: { confirm: "Do you really want to delete this" } do %>
    <i class="fa fa-trash trash-btn"></i>
    <span>All delete</span>
  <% end %>
  <hr>
<% if @notifications.exists? %>
  <div class="notification-index">
    <%= render @notifications %>
  </div>
<% else %>
  <p>No notifications/p>
<% end %>