config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      delete 'destroy_all'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts,          only: [:show,:create, :destroy] do 
    resources :comments,         only: [:create, :destroy]
    resource :likes,                    only:[:create, :destroy]
    collection do
      get 'search'
    end
  end 
  resources :notifications,        only:[:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_microposts, through: :likes, source: :micropost
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                                      foreign_key: "follower_id",
                                                      dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                                      foreign_key: "followed_id",
                                                      dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :full_name, presence: true, length: { maximum: 50 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :introduction, length: {maximum:140}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                          format: { with: VALID_EMAIL_REGEX },
                          uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    self.update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  # attribute: remember, activation, reset
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送る
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
    # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

      # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

 # ユーザーのステータスフィードを返す
 def feed
  following_ids = "SELECT followed_id FROM relationships
  WHERE follower_id = :user_id"
  Micropost.where("user_id IN (#{following_ids})
  OR user_id = :user_id", user_id: id)
end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end
  
  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end  

  # フォロー通知
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end
    
  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy,
                                                                :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
# GET/users
  def index
    @users = User.paginate(page: params[:page])
  end
# GET/users/:id 
  def show
    @user = User.find(params[:id])
    @micropost = Micropost.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    @comments = @micropost.comments
    @comment = Comment.new
  end
# GET/users/new
  def new
    @user = User.new
  end
# POST/users
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
      # success(valid params)
    else
      # Failure(not valid params)
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      flash.now[:danger] = "Profile editing failed"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def destroy_all
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User withdrawn"
    redirect_to root_path
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:full_name, :name, :email, :gender, :phone_number,
                                                  :introduction, :password, :password_cofirmation)
  end

    # beforeアクション

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # 管理者かどうか確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_comment.html.erb
<div class="micropost-container">
  <div class="text-center">
    <%= image_tag micropost.display_image if micropost.image.attached? %>
  </div>
  <div class="text-left">
    <%= micropost.content %>
  </div>
</div>
<br>
<hr>
<div class="card mb-4">
  <div class="card-content">
    <div id="comments_area">
      <% @comments.each do |comment| %>
        <div class="comment-name">
          <%= link_to comment.user.name, [comment.user] %>
        </div>
        <div class="comment-content">
          <%= comment.content %>
        </div>
        <div class="comment-index">
          <% if comment.user == current_user %>
              <%= time_ago_in_words(comment.created_at) %>ago.
            | <%= link_to 'Delete', [micropost, comment], method: :delete, remote: true %>
              <hr>
          <% else %>
          <div class="comment-delete">
            <%= time_ago_in_words(comment.created_at) %>ago.
            <hr>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if logged_in? %>
      <% if comment.errors.any? %>
        <% comment.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <%= form_with model: [micropost, comment], local: true, remote: true do |f| %>
      <div class="field">
        <%= f.text_area :content, class: 'input', placeholder: "Comment" %>
      </div>
      <%= f.submit "To comment", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div> 

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
                          html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<ul class="users">
  <li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
  </li>
</ul>

app/views/users/edit.html.erb
<% set_meta_tags title: 'ユーザー編集', description: 'Inssta Cloneのアカウント情報の編集画面です。' %>

<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>

<h1>Update your profile</h1>
<div class="row">
  <div class="gravatar_edit">
    <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">profile change</a>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="edit-container">
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :full_name %>
        <%= f.text_field :full_name, class: 'form-control' %>
        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: 'form-control' %>
          <div class="male-btn">
            <%= f.radio_button :gender, :male, class: "male-btn" %>
            <%= f.label :gender, "男性", value: :male, class: "male-label" %>
          </div>
          <div class="female-btn">
            <%= f.radio_button :gender, :female, class: "female-btn" %>
            <%= f.label :gender, "女性", value: :female, class: "female-label" %>
          </div>
          <p>※private</p>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <p>※private</p>

        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: "form-control" %>
        <p>※private</p>

        <%= f.label :web_site %>
        <%= f.text_field :web_site, class: 'form-control', value: @user.web_site, placeholder: "https://www.insta_clone.com" %>

        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control", value: @user.introduction %>
        <br>
        <%= f.submit 'Save changes', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>
<br>
<div class="withdrawal text-right">
  <%= link_to "Withdraw", destroy_all_user_path(@user), method: :delete,
                          data: { confirm: "Do you really want to unsubscribe" } %>
</div>

app/views/users/index.html.erb
<% set_meta_tags title: 'すべてのユーザー', description: 'Inssta Cloneのすべてのユーザーページです。' %>

<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "Do you really want to unsubscribe" } %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% set_meta_tags title: '新規登録', description: 'Inssta Cloneの新規登録画面です。' %>

<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="new-container">
      <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :full_name %>
      <%= f.text_field :full_name, class: "form-control", placeholder: "takahashi toshiaki" %>
      <p>privacy</p>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <div class="terms_of_service text-center">
        <%= link_to "terms_of_service", terms_of_service_path %> / 
        <%= link_to "privacy_policy", privacy_policy_path %>
      </div>
      <br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% set_meta_tags title: 'プロフィール', description: 'Inssta Cloneアカウントのプロフィール画面です。' %>
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
    <%= render 'shared/stats' %>
    </section>
    <section class="introduction">
      <div class="introduction-title">
        <i class="fa fa-user"></i> Introduction
        </div>
        <p><%= @user.introduction %></p>
    </section>
    <section class="web-site">
     <div class="web-site-title">
      <i class="fa fa-globe"></i>Website
      </div>
      <p><%= link_to @user.web_site %></p>
    </section>
    <section>
      <%= render 'follow_form' if logged_in? %>
    </section>
  </aside>

  <div class="col-md-8">
  <% if @user.microposts.any? %>
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <hr>
    <ol class="microposts">
    <%= render @microposts %>
    </ol>
      <%= will_paginate @microposts %>
      <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% set_meta_tags title: 'フォロー/フォロワー', description: 'Inssta Cloneのフォロー/フォロワーの一覧です。' %>

<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <li><%= render @users %></li>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>