config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
      delete 'destroy_all'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts,          only: [:show,:create, :destroy] do 
    resources :comments,         only: [:create, :destroy]
    resource :likes,                    only:[:create, :destroy]
    collection do
      get 'search'
    end
  end 
  resources :notifications,        only:[:index, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end
end

app/views/layouts/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-F1LTPJN2BL"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-F1LTPJN2BL');
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="
    #">Insta Clone</a>
    By <a href="#">Toshiaki Takahashi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Terms_of_service",   terms_of_service_path %></li>
      <li><%= link_to "Privacy_policy", privacy_policy_path %></li>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Insta Clone", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <%= link_to root_path do %>
          <i class="fa fa-home"></i>
        <% end %>
        </li>
        <% if logged_in? %>
        <li>
          <%= link_to root_path do%>
          <i class="fa fa-upload fa-2x"></i>
          <% end %>
        </li>
        <%= render "notifications/circle" %>
        <li>
          <%= link_to search_microposts_path do %>
          <i class="fa fa-search fa-2x"></i>
          <% end %>
        </li>
        <li>  
          <%= link_to users_path do %>
          <i class="fa fa-users fa-2x"></i>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-user fa-2x"></i> <b class="caret"></b>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Profile", current_user %>
            </li>
            <li>
              <%= link_to "Settings", edit_user_path(current_user) %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to "Log in", login_path %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render 'layouts/analytics' %>
  <%= display_meta_tags(default_meta_tags) %>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <![endif]-->
  </head>   
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>